name: Translate to French

on:
  push:
    branches: [ main, master ]
    paths:
      - 'locales/xx.json'

jobs:
  translate-to-french:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout guide repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 2  # Fetch the current and previous commit

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Translate modified parts of xx.json to French
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      id: translate
      run: |
        cat > translate_to_french.py << 'EOL'
        import json
        import os
        import time
        import sys
        import difflib
        import re
        import subprocess
        from openai import OpenAI

        # Function to log with timestamps
        def log_with_time(message):
            timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
            print(f"[{timestamp}] {message}")
            sys.stdout.flush()  # Force output to be written immediately

        start_time = time.time()
        log_with_time("Starting translation process")

        # Get previous and current versions of xx.json
        log_with_time("Getting previous version of xx.json")
        try:
            # Get the hash of the previous commit
            prev_hash = subprocess.check_output(
                ['git', 'rev-parse', 'HEAD~1'],
                universal_newlines=True
            ).strip()
            
            # Get the previous version of xx.json
            prev_content = subprocess.check_output(
                ['git', 'show', f'{prev_hash}:locales/xx.json'],
                universal_newlines=True
            )
            prev_data = json.loads(prev_content)
            prev_page_content = prev_data.get('page-content', '')
            
            log_with_time("Successfully loaded previous version of xx.json")
        except Exception as e:
            log_with_time(f"Error getting previous version: {e}")
            log_with_time("Will translate the entire file as fallback")
            prev_page_content = ""

        # Load the current xx.json file
        log_with_time("Loading current xx.json file")
        with open('locales/xx.json', 'r', encoding='utf-8') as file:
            current_data = json.load(file)
            
        # Extract the current page-content
        log_with_time("Extracting current page-content")
        current_page_content = current_data.get('page-content', '')
        if not current_page_content:
            raise Exception("No 'page-content' found in xx.json")
            
        # Check if we need to translate existing fr.json
        fr_exists = os.path.exists('locales/fr.json')
        fr_data = {}
        if fr_exists:
            log_with_time("Found existing fr.json, loading it")
            with open('locales/fr.json', 'r', encoding='utf-8') as file:
                fr_data = json.load(file)
                
        # Initialize translation base (what we'll start with)
        translation_base = fr_data.get('page-content', '') if fr_exists else ''
            
        # Initialize OpenAI API
        log_with_time("Initializing OpenAI API client")
        client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
        
        # Function to find HTML blocks that have changed
        def find_changed_blocks(prev_html, current_html):
            log_with_time("Finding changed HTML blocks")
            
            if not prev_html:
                log_with_time("No previous content found, will translate everything")
                return [current_html]  # If no previous content, return the entire current content
                
            # Create a diff of the HTML content
            differ = difflib.Differ()
            diff = list(differ.compare(prev_html.splitlines(), current_html.splitlines()))
            
            # Extract changed sections with context
            changed_blocks = []
            in_change_block = False
            current_block = []
            context_lines = 3  # Number of lines of context to include
            
            for i, line in enumerate(diff):
                if line.startswith('+ ') or line.startswith('- '):  # Changed line
                    if not in_change_block:
                        in_change_block = True
                        # Add context before
                        start_context = max(0, i - context_lines)
                        for j in range(start_context, i):
                            if diff[j].startswith('  '):  # Unchanged line
                                current_block.append(diff[j][2:])
                    
                    if line.startswith('+ '):  # Added line
                        current_block.append(line[2:])
                
                elif line.startswith('  '):  # Unchanged line
                    if in_change_block:
                        current_block.append(line[2:])
                        # Check if we should end the block
                        end_context_count = 0
                        for j in range(i+1, min(i+1+context_lines, len(diff))):
                            if diff[j].startswith('  '):
                                end_context_count += 1
                            else:
                                break
                        
                        if end_context_count == context_lines:
                            # We have enough unchanged context, end the block
                            changed_blocks.append('\n'.join(current_block))
                            current_block = []
                            in_change_block = False
            
            # If we're still in a change block at the end
            if in_change_block and current_block:
                changed_blocks.append('\n'.join(current_block))
            
            # If no blocks were detected, return the whole content
            if not changed_blocks:
                log_with_time("No specific changes detected, will translate everything")
                return [current_html]
                
            log_with_time(f"Found {len(changed_blocks)} changed blocks")
            return changed_blocks
        
        # Find the blocks that need to be translated
        blocks_to_translate = find_changed_blocks(prev_page_content, current_page_content)
        
        # Function to translate a block
        def translate_block(block, block_index, total_blocks):
            log_with_time(f"Translating block {block_index+1}/{total_blocks} ({len(block)} characters)")
            
            translation_start = time.time()
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "Translate the given HTML content into French while keeping all HTML tags and structure intact. Use widely accepted French football terminology. Maintain authenticity and precision without altering the original meaning. Output only the translations without any additional text or markdown."},
                    {"role": "user", "content": block}
                ],
                temperature=0.7,
            )
            translation_end = time.time()
            
            log_with_time(f"Block {block_index+1} translated in {(translation_end - translation_start):.2f} seconds")
            
            translated_block = response.choices[0].message.content
            if translated_block.startswith("```") and translated_block.endswith("```"):
                translated_block = re.sub(r'^```.*\n', '', translated_block)
                translated_block = re.sub(r'\n```$', '', translated_block)
                
            return translated_block
        
        # Update the fr.json file
        if len(blocks_to_translate) == 1 and blocks_to_translate[0] == current_page_content:
            # If we're translating the entire content
            log_with_time("Translating the entire page content")
            if len(current_page_content) > 6000:
                # Process large content in chunks as in the original script
                # (Code for chunking large content would go here, similar to the original)
                # ...
                log_with_time("Content is large, processing in batches")
                
                # Split content into manageable chunks based on HTML structure
                chunks = []
                current_position = 0
                
                # Function to find a good split point
                def find_split_point(text, start_pos, chunk_size=6000):
                    end_pos = min(start_pos + chunk_size, len(text))
                    if end_pos >= len(text):
                        return len(text)
                    
                    # Look for end of section/div tags as good split points
                    for marker in ['</section>', '</div>']:
                        marker_pos = text.rfind(marker, start_pos, end_pos)
                        if marker_pos != -1:
                            return marker_pos + len(marker)
                    
                    # If no good split point found, look for end of paragraph
                    paragraph_end = text.rfind('</p>', start_pos, end_pos)
                    if paragraph_end != -1:
                        return paragraph_end + 4
                    
                    # Fallback to sentence end
                    for punct in ['. ', '! ', '? ']:
                        punct_pos = text.rfind(punct, start_pos, end_pos)
                        if punct_pos != -1:
                            return punct_pos + 2
                    
                    # Last resort: just split at chunk_size
                    return end_pos
                
                # Split content into chunks
                while current_position < len(current_page_content):
                    split_point = find_split_point(current_page_content, current_position)
                    chunk = current_page_content[current_position:split_point]
                    chunks.append(chunk)
                    current_position = split_point
                
                log_with_time(f"Split content into {len(chunks)} chunks")
                
                # Translate each chunk separately
                translated_chunks = []
                for i, chunk in enumerate(chunks):
                    translated_chunk = translate_block(chunk, i, len(chunks))
                    translated_chunks.append(translated_chunk)
                
                # Combine all translated chunks
                log_with_time("Combining all translated chunks")
                translated_content = "".join(translated_chunks)
            else:
                # Translate the whole content at once
                translated_content = translate_block(current_page_content, 0, 1)
        else:
            # If we're translating specific blocks
            log_with_time(f"Translating {len(blocks_to_translate)} modified blocks")
            
            # Start with the current translation if available
            if translation_base:
                log_with_time("Using existing French translation as base")
                translated_content = translation_base
            else:
                # If no existing translation, translate everything
                log_with_time("No existing translation found, translating everything")
                translated_content = translate_block(current_page_content, 0, 1)
                
            # Translate each modified block and update the content
            for i, block in enumerate(blocks_to_translate):
                if translation_base:  # Only attempt to replace if we have a base translation
                    translated_block = translate_block(block, i, len(blocks_to_translate))
                    
                    # Find where this block should go in the original content
                    # This is simplified and might need improvement for complex changes
                    # A more robust approach would be to track the position of each block in the original
                    # and apply changes in order from end to beginning to avoid position shifts
                    block_start = current_page_content.find(block)
                    if block_start != -1:
                        log_with_time(f"Found position of block {i+1} in original content")
                        # Find the corresponding position in the translated content
                        # This is a simplification and might not work perfectly for all cases
                        ratio = len(translated_content) / len(current_page_content)
                        estimated_pos = int(block_start * ratio)
                        
                        # Search around the estimated position for key elements from before/after the block
                        # This is a complex problem that might require more sophisticated matching
                        
                        # For now, just replace the next occurrence of a similar pattern
                        # This is a placeholder for a more robust approach
                        log_with_time(f"Updating translated content with block {i+1}")
                        translated_content = translated_content[:estimated_pos] + translated_block + translated_content[estimated_pos + len(translated_block):]
        
        # Create the fr.json file
        log_with_time("Creating fr.json file")
        fr_data = {
            "common": {"nav": {"players": "Joueurs","pro": "Pro","teams": "Équipes"}},
            "meta": {"title": "DataMB | Guide","description": "Explication des outils, des statistiques et de la méthodologie utilisés par DataMB"},
            "search": {"placeholder": "Cherchez une équipe ou joueur..."},
            "page-content": translated_content
        }
        
        os.makedirs('locales', exist_ok=True)
        with open('locales/fr.json', 'w', encoding='utf-8') as json_file:
            json.dump(fr_data, json_file, ensure_ascii=False, indent=2)

        total_time = time.time() - start_time
        log_with_time(f"Translated content saved to locales/fr.json. Total execution time: {total_time:.2f} seconds")
        EOL

        python translate_to_french.py

    - name: Commit and push French translation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add locales/fr.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-translate xx.json to French"
        git push

    - name: Checkout proguide repo
      uses: actions/checkout@v3
      with:
        repository: ohlitmybad/proguide
        path: proguide
        token: ${{ secrets.PAT }}

    - name: Commit and push proguide changes
      run: |
        cd proguide
        mkdir -p locales
        cp $GITHUB_WORKSPACE/locales/fr.json locales/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html locales/fr.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-translate xx.json to French"
        git push
