name: Update Guide and ProGuide

on:
  push:
    branches: [ main, master ]
    paths:
      - 'index.html'

jobs:
  update-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout guide repo
      uses: actions/checkout@v3
      with:
        path: guide
        token: ${{ secrets.PAT }}
        
    - name: Checkout proguide repo
      uses: actions/checkout@v3
      with:
        repository: ohlitmybad/proguide
        path: proguide
        token: ${{ secrets.PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        
    - name: Sync content and update files
      run: |
        cat > sync_repos.py << 'EOL'
        import json
        from bs4 import BeautifulSoup
        import os
        import re

        # Process guide repo first
        print("Processing guide repo...")
        
        # Load the HTML file from guide
        with open('guide/index.html', 'r', encoding='utf-8') as file:
            guide_html_content = file.read()
        
        # The div is the last one in the document
        # Extract content between opening div with data-i18n="page-content" and the last closing div
        page_content_match = re.search(r'<div[^>]*data-i18n="page-content"[^>]*>(.*)</div>$', 
                                      guide_html_content, re.DOTALL)
        
        if not page_content_match:
            raise Exception("Could not find div with data-i18n='page-content' in guide repo")
        
        # Get the inner content
        guide_inner_content = page_content_match.group(1)
        
        # Create JSON object for guide - using only the inner content
        guide_json_obj = {"page-content": guide_inner_content}
        
        # Write to guide en.json
        os.makedirs('guide/locales', exist_ok=True)
        with open('guide/locales/en.json', 'w', encoding='utf-8') as json_file:
            json.dump(guide_json_obj, json_file, ensure_ascii=False, indent=2)
        
        print("Updated guide/locales/en.json successfully!")
        
        # Now process proguide repo
        print("Processing proguide repo...")
        
        # Load the HTML file from proguide
        with open('proguide/index.html', 'r', encoding='utf-8') as file:
            proguide_html_content = file.read()
        
        # Replace exactly between the opening page-content div and the last closing div
        # This ensures the exact replacement at the same position
        pattern = r'(<div[^>]*data-i18n="page-content"[^>]*>).*?(</div>$)'
        replacement = r'\1' + guide_inner_content + r'\2'
        
        # Replace the content - maintaining exact same positions
        updated_proguide_html = re.sub(pattern, replacement, proguide_html_content, flags=re.DOTALL)
        
        # Write updated HTML back to proguide index.html
        with open('proguide/index.html', 'w', encoding='utf-8') as file:
            file.write(updated_proguide_html)
        
        print("Updated proguide/index.html successfully!")
        
        # Create JSON object for proguide (same content as guide)
        proguide_json_obj = {"page-content": guide_inner_content}
        
        # Write to proguide en.json
        os.makedirs('proguide/locales', exist_ok=True)
        with open('proguide/locales/en.json', 'w', encoding='utf-8') as json_file:
            json.dump(proguide_json_obj, json_file, ensure_ascii=False, indent=2)
        
        print("Updated proguide/locales/en.json successfully!")
        EOL
        
        python sync_repos.py
        
    - name: Commit and push guide changes
      run: |
        cd guide
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add locales/en.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update en.json automatically"
        git push
        
    - name: Commit and push proguide changes
      run: |
        cd proguide
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html locales/en.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync content from guide repo"
        git push
