name: Update Localization Files

on:
  push:
    branches: [ main, master ]
    paths:
      - 'index.html'

jobs:
  update-locales:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        
    - name: Create and run script
      run: |
        cat > update_locales.py << 'EOL'
        import json
        from bs4 import BeautifulSoup

        # Load the HTML file
        with open('index.html', 'r', encoding='utf-8') as file:
            html_content = file.read()

        # Parse the HTML
        soup = BeautifulSoup(html_content, 'html.parser')

        # Find the div with data-i18n="page-content"
        div_content = soup.find('div', attrs={'data-i18n': 'page-content'})

        # Create JSON object
        json_obj = {"page-content": str(div_content)}

        # Write to en.json
        with open('locales/en.json', 'w', encoding='utf-8') as json_file:
            json.dump(json_obj, json_file, ensure_ascii=False, indent=2)

        print("en.json file created successfully!")
        EOL
        
        python update_locales.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add locales/en.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update en.json automatically"
        git push
