name: Update en.json on index.html change

on:
  push:
    branches: [ main, master ]
    paths:
      - 'index.html'

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        
    - name: Update en.json
      run: |
        python -c "
import json
from bs4 import BeautifulSoup

# Load the HTML file
with open('index.html', 'r', encoding='utf-8') as file:
    html_content = file.read()

# Parse the HTML
soup = BeautifulSoup(html_content, 'html.parser')

# Find the div with data-i18n=\"page-content\"
div_content = soup.find('div', attrs={'data-i18n': 'page-content'})

# Create JSON object
json_obj = {\"page-content\": str(div_content)}

# Write to en.json
with open('locales/en.json', 'w', encoding='utf-8') as json_file:
    json.dump(json_obj, json_file, ensure_ascii=False, indent=2)

print(\"en.json file updated successfully!\")
        "
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add locales/en.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update en.json from index.html"
        git push
